#server:
#  port: 8876
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

server:
  port: 8989
spring:
  application:
    name: 'shopping-sellergoods-ms'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougodb1
    username: root
    password: 123456

pagehelper:
  helper-dialect: mysql
  reasonable: true
